<?php

namespace AppBundle\Repository;

/**
 * GeographyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeographyRepository extends \Doctrine\ORM\EntityRepository
{
}
