<?php

namespace AppBundle\Repository;

/**
 * SavePostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SavePostRepository extends \Doctrine\ORM\EntityRepository
{
}
