<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFkjtj7k\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFkjtj7k/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFkjtj7k.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFkjtj7k\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFkjtj7k\appProdProjectContainer(array(
    'container.build_hash' => 'Fkjtj7k',
    'container.build_id' => '4b50db5c',
    'container.build_time' => 1542956410,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFkjtj7k');
